name: icab
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.3+1
  firebase_auth: ^0.15.5+2
  firebase_database: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - images/car_green.svg
   - images/car_red.svg
   - images/ic_lock.svg
   - images/ic_mail.svg
   - images/ic_phone.svg
   - images/ic_user.svg

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito_Regular.ttf
        - asset: fonts/Nunito_Italic.ttf
          style: italic
        - asset: fonts/Nunito_SemiBold.ttf
          weight: 700
        # - asset: fonts/Nunito_SemiBoldItalic.ttf
        # - asset: fonts/Nunito_Light.ttf
        # - asset: fonts/Nunito_LightItalic.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
